name: API Automation - Rest Assured + Allure

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  api-tests:
    runs-on: ubuntu-latest

    env:
      BASE_URL: ${{ secrets.BASE_URL }}
      USERNAME: ${{ secrets.BOOKER_USERNAME }}
      PASSWORD: ${{ secrets.BOOKER_PASSWORD }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Build and Run Tests
        run: mvn clean test

      # Debug step (can remove later)
      - name: Debug Target Folder
        if: always()
        run: ls -R target || true

      - name: Upload Allure Raw Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: target/allure-results
          if-no-files-found: warn

      - name: Generate Allure Report
        if: always()
        run: mvn allure:report

      - name: Upload Allure HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: target/site/allure-maven-plugin
          if-no-files-found: warn